DonationManager/Controllers/CharitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DonationManager.Data;
using DonationManager.Models;

namespace DonationManager.Controllers
{
    public class CharitiesController : Controller
    {
        private DonationManagerContext db = new DonationManagerContext();

        // GET: Charities
        public ActionResult Index(string searchTerm)
        {
            ViewBag.noResults = false;
            var charities = from c in db.Charities select c;
            if (!String.IsNullOrEmpty(searchTerm))
            {
                charities = charities.Where(c => c.Name.Contains(searchTerm)
                || c.OfficialName.Contains(searchTerm)
                || c.Details.Contains(searchTerm)
                || c.Type.Contains(searchTerm)
                || c.Notes.Contains(searchTerm));
                if (charities.Count() == 0)
                {
                    return RedirectToAction("SearchResults");
                }
            }            
            charities = charities.OrderBy(c => c.Name);
            return View(charities.ToList());
        }

        // GET: Search results (for empty search results)
        public ActionResult SearchResults()
        {
            return View();
        }

        // GET: Charities/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Charity charity = db.Charities.Find(id);
            if (charity == null)
            {
                return HttpNotFound();
            }
            return View(charity);
        }

        // GET: Charities/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Charities/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,OfficialName,CharityNumber,PreferredMethod,Details,Type,Notes")] Charity charity)
        {
            if (ModelState.IsValid)
            {
                db.Charities.Add(charity);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = charity.ID });
            }

            return View(charity);
        }

        // GET: Charities/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Charity charity = db.Charities.Find(id);
            if (charity == null)
            {
                return HttpNotFound();
            }
            return View(charity);
        }

        // POST: Charities/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,OfficialName,PreferredMethod,CharityNumber,Details,Type,Notes")] Charity charity)
        {
            if (ModelState.IsValid)
            {
                db.Entry(charity).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = charity.ID });
            }
            return View(charity);
        }

        // POST: Charities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Charity charity = db.Charities.Find(id);
            db.Charities.Remove(charity);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DonationManager/Controllers/DonationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DonationManager.Data;
using DonationManager.Models;

namespace DonationManager.Controllers
{
    public class DonationsController : Controller
    {
        private DonationManagerContext db = new DonationManagerContext();

        // GET: Donations
        public ActionResult Index()
        {
            var donations = db.Donations.Include(d => d.Charity);
            return View(donations.ToList());
        }

        // GET: Donations Parial Index

        public PartialViewResult PartialIndex(int id)
        {
            ViewBag.ID = id;
            var donations = from d in db.Donations select d;
            donations = donations.Include(d => d.Charity);
            donations = donations.Where(d => d.Charity.ID.Equals(id));
            donations = donations.OrderByDescending(d => d.Date);
            return PartialView(donations.ToList());
        }

        // GET: Donations/Create
        public PartialViewResult Create(bool isModal, int? id)
        {
            ViewBag.ID = id;
            ViewBag.CharityID = new SelectList(db.Charities.OrderBy(c => c.Name), "ID", "Name");
            ViewBag.PersonID = new SelectList(db.People, "ID", "FirstName");
            return PartialView();

        }

        // POST: Donations/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Date,Amount,Note,Method,CharityID")] Donation donation)
        {
            if (ModelState.IsValid)
            {
                db.Donations.Add(donation);
                db.SaveChanges();
                return RedirectToAction("Details", "Charities", new { id = donation.CharityID });
            }

            ViewBag.CharityID = new SelectList(db.Charities.OrderBy(c => c.Name), "ID", "Name", donation.CharityID);
            return View(donation);
        }

        // GET: Donations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Donation donation = db.Donations.Find(id);
            if (donation == null)
            {
                return HttpNotFound();
            }
            ViewBag.CharityID = new SelectList(db.Charities.OrderBy(c => c.Name), "ID", "Name", donation.CharityID);
            return View(donation);
        }

        // POST: Donations/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Date,Amount,Note,Method,CharityID,Charity")] Donation donation)
        {            
            if (ModelState.IsValid)
            {
                db.Entry(donation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("details","charities", new { id = donation.CharityID });
            }
            ViewBag.CharityID = new SelectList(db.Charities.OrderBy(c => c.Name), "ID", "Name", donation.CharityID);
            return View(donation);
        }

        // GET: AJAX Edit modal
        public ActionResult OpenEditModal(string id)
        {
            Donation donation = db.Donations.Find(int.Parse(id));
            if (donation == null)
            {
                return HttpNotFound();
            }
            ViewBag.CharityID = new SelectList(db.Charities.OrderBy(c => c.Name), "ID", "Name", donation.CharityID);
            return PartialView("EditModal", donation);
        }

        // GET: AJAX Delete modal
        public ActionResult OpenDeleteModal(string id)
        {
            int Id = int.Parse(id);
            var donation = from d in db.Donations select d;
            donation = donation.Include(d => d.Charity);
            donation = donation.Where(d => d.ID.Equals(Id));
            var donationList = donation.ToList();           
            if (donation == null)
            {
                return HttpNotFound();
            }            
            return PartialView("DeleteModal", donationList.ElementAt(0));
        }

        // POST: Donations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Donation donation = db.Donations.Find(id);
            db.Donations.Remove(donation);
            db.SaveChanges();            
            return RedirectToAction("Details","Charities",new { id = donation.CharityID });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DonationManager/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DonationManager.Data;
using DonationManager.Models;

namespace DonationManager.Controllers
{
    public class PeopleController : Controller
    {
        private DonationManagerContext db = new DonationManagerContext();

        // GET: People
        public ActionResult Index()
        {
            return View(db.People.ToList());
        }

        // GET: People/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.People.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        // GET: People/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: People/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,FirstName,LastName,Email,Phone")] Person person)
        {
            if (ModelState.IsValid)
            {
                db.People.Add(person);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(person);
        }

        // GET: People/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.People.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        // POST: People/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,FirstName,LastName,Email,Phone")] Person person)
        {
            if (ModelState.IsValid)
            {
                db.Entry(person).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(person);
        }

        // GET: People/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.People.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        // POST: People/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Person person = db.People.Find(id);
            db.People.Remove(person);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DonationManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
</head>
<body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href=@Url.Action("Index", "Home")>
                Donation Manager
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item">
                <a class="nav-link" href=@Url.Action("Index", "Home")>
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <!--<div class="sidebar-heading">
                Interface
            </div>-->
            <!-- Nav Item - Pages Collapse Menu -->
            <!--<li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                   aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Components</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Custom Components:</h6>
                        <a class="collapse-item" href="buttons.html">Buttons</a>
                        <a class="collapse-item" href="cards.html">Cards</a>
                    </div>
                </div>
            </li>-->

            <li class="nav-item">
                <a class="nav-link" href=@Url.Action("Index", "Charities")>
                    <i class="fas fa-fw fa-building"></i>
                    <span>Charities</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href=@Url.Action("Index", "People")>
                    <i class="fas fa-fw fa-users"></i>
                    <span>Contacts</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href=@Url.Action("Index", "Donations")>
                    <i class="fas fa-fw fa-donate"></i>
                    <span>Donations</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <li class="nav-item">
                <a class="nav-link" href=@Url.Action("ImportData","Home")>
                    <i class="fas fa-fw fa-file-upload"></i>
                    <span>Import Data <br /><small class="badge badge-info badge-pill">Coming soon...</small></span>
                </a>                
            </li>
            <li class="nav-item">
                <a class="nav-link" href=@Url.Action("Reports","Home")>
                    <i class="fas fa-fw fa-chart-line"></i>
                    <span>Reports <br /><small class="badge badge-info badge-pill">Coming soon...</small></span>

                </a>
                
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>
        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Topbar Search -->
                    <form action="~/Charities/Index" class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                        <div class="input-group">
                            <input type="text" name="searchTerm" class="form-control bg-light border-0 small" placeholder="Search for..."
                                   aria-label="Search" aria-describedby="basic-addon2" />
                            <div class="input-group-append">
                                <span class="btn btn-primary">
                                    <i class="fas fa-search fa-sm"></i>
                                </span>
                            </div>
                        </div>
                    </form>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                 aria-labelledby="searchDropdown">
                                <form action="~/Charities/Index" class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                               placeholder="Search for..." name="searchTerm" aria-label="Search"
                                               aria-describedby="basic-addon2" />
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>

                        <div class="topbar-divider d-none d-sm-block"></div>
               
                        <!--start login-->
                        @using Microsoft.AspNet.Identity
                        @if (Request.IsAuthenticated)
                        {
                            using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "ml-auto" }))
                            {
                                @Html.AntiForgeryToken()

                                <ul class="nav navbar-nav ml-auto">

                                    <li class="nav-item dropdown no-arrow">
                                        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <span class="mr-2 d-none d-lg-inline text-gray-600 small">@User.Identity.Name</span>
                                            <i class="fa fa-user-circle"></i>
                                            @*<img class="img-profile rounded-circle"
                                                src="img/undraw_profile.svg">*@
                                        </a>
                                        <!-- Dropdown - User Information -->
                                        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                             aria-labelledby="userDropdown">
                                            <a class="dropdown-item" href=@Url.Action("index", "Manage")>
                                                <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                                Profile
                                            </a>
                                            @*<a class="dropdown-item" href="#">
                                                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                                    Settings
                                                </a>
                                                <a class="dropdown-item" href="#">
                                                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                                                    Activity Log
                                                </a>
                                                <div class="dropdown-divider"></div>*@
                                            <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                                <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                                Logout
                                            </a>
                                        </div>
                                    </li>

                                    @*<li>
                                            @Html.ActionLink("Hello " + User.Identity.GetUserName() + "!", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage", @class = "nav-link" })
                                        </li>
                                        <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>*@
                                </ul>
                            }
                        }
                        else
                        {
                            <ul class="nav navbar-nav ml-auto">
                                <li>@Html.ActionLink("Register", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink", @class = "nav-link" })</li>
                                <li>@Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink", @class = "nav-link" })</li>
                            </ul>
                        }

                        <!--End login-->
                    </ul>

                </nav>

                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <!-- /.container-fluid -->
                <div class="container-fluid" id="page-content">

                    <!-- Page Heading -->
                    @Scripts.Render("~/bundles/jquery")

                    @RenderBody()

                </div>
            </div>

            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; 2021, Naftoli Ost</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" to log out of your account</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-danger" href="javascript:document.getElementById('logoutForm').submit()">Logout</a>
                </div>
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/bootstrap")

    <!-- Core plugin JavaScript-->
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>

    <!-- Page level plugin JavaScript-->
    <script src="~/Scripts/vendor/chart.js/Chart.min.js"></script>
    <script src="~/Scripts/vendor/datatables/jquery.dataTables.js"></script>
    <script src="~/Scripts/vendor/datatables/dataTables.bootstrap4.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/Scripts/sb-admin.min.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>